-- MySQL Script generated by MySQL Workbench
-- Thu Sep  5 13:33:11 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema IF_livros
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema IF_livros
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `IF_livros` ;
USE `IF_livros` ;

-- -----------------------------------------------------
-- Table `IF_livros`.`livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IF_livros`.`livro` (
  `idlivros` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `autor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idlivros`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IF_livros`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IF_livros`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  `telefone` VARCHAR(20) NULL,
  `email` VARCHAR(100) NULL,
  `data_de_nascimento` DATE NOT NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IF_livros`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IF_livros`.`funcionario` (
  `idfuncionario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `data_de_nascimento` DATE NOT NULL,
  `funcao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idfuncionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IF_livros`.`emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IF_livros`.`emprestimo` (
  `emprestimo` INT NOT NULL AUTO_INCREMENT,
  `data_de_devolucao` DATE NOT NULL,
  `data_de_emprestimo` DATE NOT NULL,
  `funcionario_idfuncionario` INT NOT NULL,
  `livro_idlivros` INT NOT NULL,
  `cliente_idcliente` INT NOT NULL,
  PRIMARY KEY (`emprestimo`),
  INDEX `fk_emprestimo_funcionario1_idx` (`funcionario_idfuncionario` ASC) VISIBLE,
  INDEX `fk_emprestimo_livro1_idx` (`livro_idlivros` ASC) VISIBLE,
  INDEX `fk_emprestimo_cliente1_idx` (`cliente_idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_emprestimo_funcionario1`
    FOREIGN KEY (`funcionario_idfuncionario`)
    REFERENCES `IF_livros`.`funcionario` (`idfuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emprestimo_livro1`
    FOREIGN KEY (`livro_idlivros`)
    REFERENCES `IF_livros`.`livro` (`idlivros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emprestimo_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `IF_livros`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IF_livros`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IF_livros`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
